revert: update dependency conventional-changelog-conventionalcommits to v8 (#11)
Reverts Hapag-Lloyd/fluent-bit-multiline#10 because it breaks the
release step.

```
RangeError: Invalid time value
    at committerDate (/home/runner/work/fluent-bit-multiline/fluent-bit-multiline/.release/node_modules/conventional-changelog-writer/index.js:80:30)
    at /home/runner/work/fluent-bit-multiline/fluent-bit-multiline/.release/node_modules/conventional-changelog-writer/lib/util.js:202:17
    at Array.forEach (<anonymous>)
    at processCommit (/home/runner/work/fluent-bit-multiline/fluent-bit-multiline/.release/node_modules/conventional-changelog-writer/lib/util.js:198:31)
    at /home/runner/work/fluent-bit-multiline/fluent-bit-multiline/.release/node_modules/conventional-changelog-writer/index.js:123:32 {
  pluginName: '@semantic-release/release-notes-generator'
```